server.port: 8095
management:
  endpoint:
    flowable:
      enabled: true
  web:
    exposure:
      include: '*'
  security:
    enabled: false

spring:
  datasource:
    url: jdbc:mariadb://172.30.141.139:3306/flowable?createDatabaseIfNotExist=true
    username: root
    password: exam
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
      naming:
        implicit-strategy: org.hibernate.boot.workflow.naming.ImplicitNamingStrategyComponentPathImpl