server.port: 8081

spring.datasource:
  url: jdbc:h2:mem:camunda
  username: sa
  password: sa
  driverClassName: org.h2.Driver
spring.h2.console.enabled: true

ccamunda.bpm:
  webapp:
    enabled: false
  admin-user:
    id: demo
    password: demo
    firstName: demo
  job-execution:
    enabled: true