server.port: 8084

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: demo
  job-execution:
    enabled: true

spring:
  application:
    name: wf
#  jersey:
#    application-path: engine-rest
#  rabbitmq:
#    host: localhost
#    port: 5672
#
#logging:
#  level:
#    root: info
#    com.oshaked.camunda: debug

kafka:
  address: 172.21.180.31:9092
  enabled: true
  topic:
    wf:
      receiver: wetest6